public with sharing class BatchProcessLeadsNoEmployees 
{
    /*
     * 7. Change this class to be a Batch class that does the following:
     * 
     * Start  - Identifies all leads in the system that have an empty
     *          Number of Employees field
     * 
     * Execute  - processes the leads in batches and adds the record ids 
     *            to a comma separated string.
     * 
     * Finish - writes the string out to System.debug.
     */

     /*
      * 8. Write a scheduled apex class that:
      * Starts this batch class with each batch containing a maximum of 
      * 15 records
      */
}
