public with sharing class FutureMethods 
{
    /* 
     * 1. Create a future method that updates the Lead Source
     *    on a collection of Contacts. Pick any Lead Source 
    */

    /* 
     * 3. Create a static method that queries Contacts from the database
     *    and executes the future method declared above
    */

    /*
     * 4. Refactor the method from step 1 so that the processing can be 
     *    carried out in an asychronous or synchronous context. 
     *    Note that your test should continue to work without any changes
     *    Hint: You will likely want to create a ContactUtils class.
     */
}
